// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {backend} from '../models';

export function AddCompanion(arg1:string,arg2:string):Promise<void>;

export function GetCompanions():Promise<Record<string, Array<models.Companion>>>;

export function GetCoverImage(arg1:string):Promise<string>;

export function GetInstalledGames():Promise<Array<models.Game>>;

export function GetLibraries():Promise<Array<models.Library>>;

export function GetMonitors():Promise<Array<backend.MonitorInfo>>;

export function GetRunningProtonProcesses():Promise<Array<models.ProtonProcess>>;

export function GetSteamStatus():Promise<models.SteamStatus>;

export function Greet(arg1:string):Promise<string>;

export function RemoveCompanion(arg1:string,arg2:string):Promise<void>;

export function SelectCompanionExe():Promise<string>;

export function SetFavorite(arg1:string,arg2:boolean):Promise<void>;
