// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCompanion(arg1, arg2) {
  return window['go']['main']['App']['AddCompanion'](arg1, arg2);
}

export function GetCompanions() {
  return window['go']['main']['App']['GetCompanions']();
}

export function GetInstalledGames() {
  return window['go']['main']['App']['GetInstalledGames']();
}

export function GetLibraries() {
  return window['go']['main']['App']['GetLibraries']();
}

export function GetMonitors() {
  return window['go']['main']['App']['GetMonitors']();
}

export function GetRunningProtonProcesses() {
  return window['go']['main']['App']['GetRunningProtonProcesses']();
}

export function GetSteamStatus() {
  return window['go']['main']['App']['GetSteamStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RemoveCompanion(arg1, arg2) {
  return window['go']['main']['App']['RemoveCompanion'](arg1, arg2);
}

export function SelectCompanionExe() {
  return window['go']['main']['App']['SelectCompanionExe']();
}
